### ISSUE TITLE
First Page

### ISSUE THREAD

**Issue by Jonas-Wendland** [Jonas-Wendland/Jonas-Wendland#2]
## Value Proposition

As a User i want to see an welcoming looking page

## Description

![Screenshot 2024-11-11 090646](https://github.com/user-attachments/assets/e737c5c8-51d3-4367-a52f-0160b808c11b)

## Acceptance Criteria

- [ ] The Profile Pictur should be displayed in the center
- [ ] under the Picture is the name written
- [ ] under name ist the proficenzy displayed
- [ ] it should have a nice calm background

## Tasks

- [ ] create a branch called `first-page`
- [ ] add the profile picture to the images folder
- [ ] on the Homepage add the image
- [ ] under the image should be the name displayed
- [ ] and under the name should be the proffesion displayed
