### ISSUE TITLE
About me

### ISSUE THREAD

**Issue by Jonas-Wendland** [Jonas-Wendland/Jonas-Wendland#4]
## Value Proposition

As a User I want to know more about the Dev

## Description

![Screenshot 2024-11-12 095308](https://github.com/user-attachments/assets/3e27f5e7-caad-4ae8-9162-079616775489)

## Acceptance Criteria

- [ ] A Picture should be Displayed of the Dev
- [ ] a short introduction should be displayed

## Tasks

- [ ] Create a feature branch `about-me`
- [ ] Insert an Image to the images folder
- [ ] Display the Image 
- [ ] Write a short about me
