### ISSUE TITLE
Skills Page

### ISSUE THREAD

**Issue by Jonas-Wendland** [Jonas-Wendland/Jonas-Wendland#5]
## Value Proposition

As a User i want to see the Skills of the Dev

## Description

![Screenshot 2024-11-13 094250](https://github.com/user-attachments/assets/f2cc6966-ab7e-4773-958f-55a72cc1f071)

## Acceptance Criteria

- [ ] Skills are shown with a Icon
- [ ] The Icons should have their Name Displayed
- [ ] The skills should be Displayed in an list

## Tasks

- [ ] Create a feature branch `skills`
- [ ] write down all the skills that should be shown
- [ ] search for Icons for the Skills
- [ ] Display the skills with their Icons
- [ ] Give the Icons their Name
